=== liuzhongh/liuzh-project/code-generator/src/code/org/code/generator/dom/code-generator-config_1_0.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
  The configuration element is the root element for configurations.
-->
<!ELEMENT configuration (properties?, classPathEntry*, context)>
                        
<!--
  The properties element is used to define a standard Java properties file
  that contains placeholders for use in the remainder of the configuration
  file.
-->
<!ELEMENT properties EMPTY>
<!ATTLIST properties
  resource CDATA #IMPLIED
  url CDATA #IMPLIED>
  
<!--
  The context element is used to describe a context for generating files, and the source
  tables.
-->
<!ELEMENT context (property*, jdbcConnection, javaTypeResolver?, table, commonPlugin*, plugin+)>
<!ATTLIST context id ID #REQUIRED  
  targetRuntime CDATA #IMPLIED>

<!ELEMENT commonPlugin (property*)>
<!ATTLIST commonPlugin
  templatePath CDATA #REQUIRED
  templateName CDATA #REQUIRED
  fileSuffix CDATA #IMPLIED
  fileExtension CDATA #IMPLIED
  fileTargetProject CDATA #REQUIRED
  targetPackage CDATA #IMPLIED
  override CDATA #IMPLIED>
  
<!--
  The plugin element is used to define a plugin.
-->

<!ELEMENT plugin (property*, javaTypeResolver?)>
<!ATTLIST plugin
  templatePath CDATA #REQUIRED
  templateName CDATA #REQUIRED
  fileSuffix CDATA #IMPLIED
  fileExtension CDATA #IMPLIED
  fileTargetProject CDATA #REQUIRED
  targetPackage CDATA #IMPLIED
  override CDATA #IMPLIED>
  
<!--
  The jdbcConnection element is used to describe the JDBC connection that the generator
  will use to introspect the database.
-->
<!ELEMENT jdbcConnection (property*)>
<!ATTLIST jdbcConnection 
  driverClass CDATA #REQUIRED
  connectionURL CDATA #REQUIRED
  userId CDATA #IMPLIED 
  password CDATA #IMPLIED
  remarksReporting CDATA #IMPLIED>

<!--
  The classPathEntry element is used to add the JDBC driver to the run-time classpath.
  Repeat this element as often as needed to add elements to the classpath.
-->
<!ELEMENT classPathEntry EMPTY>
<!ATTLIST classPathEntry
  location CDATA #REQUIRED>

<!--
  The property element is used to add custom properties to many of the generator's
  configuration elements.  See each element for example properties.
  Repeat this element as often as needed to add as many properties as necessary
  to the configuration element.
-->
<!ELEMENT property EMPTY>
<!ATTLIST property
  name CDATA #REQUIRED
  value CDATA #REQUIRED>

<!--
  The javaTypeResolver element is used to define properties of the Java Type Resolver.
  The Java Type Resolver is used to calculate Java types from database column information.
  The default Java Type Resolver attempts to make JDBC DECIMAL and NUMERIC types easier
  to use by substituting Integral types if possible (Long, Integer, Short, etc.)
-->
<!ELEMENT javaTypeResolver (property*)>
<!ATTLIST javaTypeResolver
  type CDATA #IMPLIED
  typeResolverImpl CDATA #IMPLIED>

<!--
  The table element is used to specify a database table that will be the source information
  for a set of generated objects.
-->
<!ELEMENT table (property*) >
<!ATTLIST table
  catalog CDATA #IMPLIED
  schema CDATA #IMPLIED
  tablesName CDATA #IMPLIED
  tableType CDATA #IMPLIED
  allTable CDATA #IMPLIED
  tablePrefix CDATA #IMPLIED>

=== liuzhongh/liuzh-project/code-generator/src/conf/codeGeneratorConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration
  SYSTEM
  "/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/code/org/code/generator/dom/code-generator-config_1_0.dtd">

<configuration>
  <classPathEntry location="/media/liuzh/A870ECF470ECCA60/work/workspace/libs/ojdbc6.jar" />

  <context id="Oracle2Tables" targetRuntime="MyBatis3">
    
    <jdbcConnection driverClass="oracle.jdbc.OracleDriver"
        connectionURL="jdbc:oracle:thin:@192.168.11.27:1521:DEVDB"
        userId="usr_mn"
        password="usr_mn321"
        remarksReporting="true">
    </jdbcConnection>

    <javaTypeResolver >
      <property name="forceBigDecimals" value="false" />
    </javaTypeResolver>

    <table schema="usr_mn" allTable="flase" tablesName="T_PROCESS_NODE,T_PROCESS_DESC,T_PROCESS_RECORD,T_NODE_CONDITION,T_PROCESS_EXECUTION" tablePrefix="T_">
    </table>
    
    <commonPlugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/action" override="false" templateName="struts.ftl" fileSuffix="" fileExtension="xml" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/web" targetPackage="base">
    	<property name="jspPath" value="base"/>
    </commonPlugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/facade" override="false" templateName="Facade.ftl" fileSuffix="Facade" fileExtension="java" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/workflow" targetPackage="com.shangkang.facade">
    	<property name="mapperPackage" value="com.shangkang.mapper"/>
    	<property name="boPackage" value="com.shangkang.bo"/>
    </plugin>

	<plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/facade" override="false" templateName="xml.ftl" fileSuffix="" fileExtension="xml" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/workflow" targetPackage="ibatis.mapper">
    	<property name="mapperPackage" value="com.shangkang.mapper"/>
    </plugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/facade" override="false" templateName="FacadeImpl.ftl" fileSuffix="FacadeImpl" fileExtension="java" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/workflow" targetPackage="com.shangkang.facade.impl">
    	<property name="boPackage" value="com.shangkang.bo"/>
    	<property name="interfacePackage" value="com.shangkang.facade"/>
    	<property name="servicePackage" value="com.shangkang.service"/>
    </plugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/service" override="false" templateName="Service.ftl" fileSuffix="Service" fileExtension="java" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/workflow" targetPackage="com.shangkang.service">
    	<property name="mapperPackage" value="com.shangkang.mapper"/>
    	<property name="boPackage" value="com.shangkang.bo"/>
    </plugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/bo" override="false" templateName="Pojo.ftl" fileSuffix="" fileExtension="java" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/workflow" targetPackage="com.shangkang.bo">
    </plugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/action" override="true" templateName="Jsp.ftl" fileSuffix="" fileExtension="jsp" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/web" targetPackage="base">
    </plugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/action" override="true" templateName="JspPopWin.ftl" fileSuffix="PopWin" fileExtension="jsp" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/web" targetPackage="base">
    </plugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/action" override="true" templateName="js.ftl" fileSuffix="" fileExtension="js" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/web" targetPackage="include.js.base">
    </plugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/mapper" override="false" templateName="Mapper.ftl" fileSuffix="Mapper" fileExtension="java" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/workflow" targetPackage="com.shangkang.mapper">
    	<property name="boPackage" value="com.shangkang.bo"/>
    </plugin>
    
    <plugin templatePath="/media/liuzh/A870ECF470ECCA60/work/workspace/code-generator/src/conf/action" override="false" templateName="Action.ftl" fileSuffix="Action" fileExtension="java" fileTargetProject="/media/liuzh/A870ECF470ECCA60/work/workspace/trans/src/workflow" targetPackage="com.shangkang.action">
    	<property name="boPackage" value="com.shangkang.bo"/>
    	<property name="facadePackage" value="com.shangkang.facade"/>
    </plugin>
    
<!--     <plugin templatePath="F:/work/workspace/code-generator/src/conf/bo" override="true" templateName="PojoAs.ftl" fileSuffix="" fileExtension="as" fileTargetProject="F:/work/workspace/3kw/flex_3kw" targetPackage="com.shangkang.front.bo"> -->
<!--     	<property name="boPackage" value="com.shangkang.bo"/> -->
<!--     	<javaTypeResolver typeResolverImpl="org.code.generator.db.types.FlexTypeResolver"> -->
<!-- 	    </javaTypeResolver> -->
<!--     </plugin> -->
    
<!--     <plugin templatePath="F:/work/workspace/code-generator/src/conf/facade" override="false" templateName="Delegate.ftl" fileSuffix="Delegate" fileExtension="as" fileTargetProject="F:/work/workspace/3kw/flex_3kw" targetPackage="com.shangkang.front.delegate"> -->
<!--     	<property name="flexBoPackage" value="com.shangkang.front.bo"/> -->
<!--     	<javaTypeResolver typeResolverImpl="org.code.generator.db.types.FlexTypeResolver"> -->
<!-- 	    </javaTypeResolver> -->
<!--     </plugin> -->
  </context>
</configuration>
